### ISSUE TITLE
invalid argument 2: view size is not compatible with input tensor's size and stride

### ISSUE THREAD

**Issue by jkkl** [snakeztc/NeuralDialog-ZSDG#3]
**** Training Begins ****
**** Epoch 0/50 ****
Train init with 1521 batches with 0 left over samples
Train add with 30 warm up batches
/home/yuanzhuo.wyz/.conda/envs/yizhen27/lib/python2.7/site-packages/torch/nn/functional.py:995: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")
Traceback (most recent call last):
  File "simdial-zsdg.py", line 174, in <module>
    main(config)
  File "simdial-zsdg.py", line 156, in main
    train(model, train_feed, valid_feed, test_feed, config, evaluator, gen=hred_utils.generate)
  File "/home/yuanzhuo.wyz/humanlike/neuraldialog-ZSDG/zsdg/main.py", line 105, in train
    loss = model(batch, mode=TEACH_FORCE)
  File "/home/yuanzhuo.wyz/.conda/envs/yizhen27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yuanzhuo.wyz/humanlike/neuraldialog-ZSDG/zsdg/models/models.py", line 499, in forward
    mode=mode, gen_type=gen_type)
  File "/home/yuanzhuo.wyz/.conda/envs/yizhen27/lib/python2.7/site-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yuanzhuo.wyz/humanlike/neuraldialog-ZSDG/zsdg/enc2dec/decoders.py", line 443, in forward
    decoder_input, decoder_hidden, attn_context, attn_words, ctx_embed)
  File "/home/yuanzhuo.wyz/humanlike/neuraldialog-ZSDG/zsdg/enc2dec/decoders.py", line 362, in forward_step
    rnn_softmax = F.softmax(self.project(output.view(-1, self.hidden_size)), dim=1)
RuntimeError: invalid argument 2: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Call .contiguous() before .view(). at /opt/conda/conda-bld/pytorch_1532571898140/work/aten/src/THC/generic/THCTensor.cpp:226
(yizhen27)

**Comment by jkkl** [comment]
when I run  command 
python simdial-zsdg.py
